[package]
name = "phasorrt-rs"
version = "4.0.0"
edition = "2024"
authors = ["Daniel McGuire"]
description = "Rust wrapper for the Phasor Runtime"

[features]
default = ["dynamic"]
dynamic = ["dep:libloading"]

[dependencies]
libloading = { version = "0.8", optional = true }
libc = "0.2"
thiserror = "1.0"

[build-dependencies]
pkg-config = "0.3"

[lib]
path = "src/Rust/lib.rs"

[[example]]
name = "test"
path = "examples/rust/bin.rs"
