// Copyright 2025-2026 Daniel McGuire
// Phasor Toolchain Licensed under the Apache License, Version 2.0 (the "License");
// Phasor Runtime Licensed under the Apache License (with Phasor Exceptions), Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// or https://phasor.pages.dev/LICENSE.txt
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once
#include <filesystem>
#include <sstream>
#include <vector>
#include <PhasorString.hpp>

/// @brief The Phasor Programming Language and Runtime
namespace Phasor
{

/**
 * @class CCodeGenerator
 * @brief Generates C++ header files with embedded Phasor bytecode
 *
 */
class CCodeGenerator
{
  public:
	/**
	 * @brief Generate a C++ header file embedding a block of Phasor VM bytecode
	 *
	 * @param bytecodeData Pointer to the serialized bytecode bytes (from compilePHS/assembleIR)
	 * @param bytecodeSize Size, in bytes, of bytecodeData
	 * @param outputPath   Path to the output header file
	 * @param moduleName   Optional module name (defaults to filename without extension)
	 * @return true if generation succeeded, false otherwise
	 */
	bool generate(const unsigned char *bytecodeData, size_t bytecodeSize, const std::filesystem::path &outputPath,
	              const Phasor::string &moduleName = "");

	/**
	 * @brief Recover the raw bytecode bytes from a header generated by generate()
	 * @param input The string containing the embedded bytecode array
	 * @return The deserialized bytecode bytes
	 */
	static std::vector<unsigned char> generateBytecodeFromEmbedded(const Phasor::string &input);

  private:
	std::ostringstream         output; ///< Output stream for generated code
	Phasor::string             moduleName;
	std::vector<unsigned char> serializedBytecode; ///< Bytecode bytes as handed to us, embedded verbatim

	// Code generation methods
	void generateFileHeader();
	void generateModuleName();
	void generateEmbeddedBytecode();

	// Deserialization helper
	static std::vector<unsigned char> parseEmbeddedBytecode(const Phasor::string &input);

	// Helper methods
	static Phasor::string escapeString(const Phasor::string &str);
	static Phasor::string sanitizeModuleName(const Phasor::string &name);
};

} // namespace Phasor