// Copyright 2025-2026 Daniel McGuire
// Phasor Toolchain Licensed under the Apache License, Version 2.0 (the "License");
// Phasor Runtime Licensed under the Apache License (with Phasor Exceptions), Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// or https://phasor.pages.dev/LICENSE.txt
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#pragma once
#include "../AST/AST.hpp"
#ifndef CMAKE_PCH
#include <Value.hpp>
#endif
#include <phsint.hpp>
#include <map>
#include <unordered_set>
#include <string>
#include <vector>
#include <optional>
#include <platform.h>

#include "Bytecode.hpp"

namespace Phasor
{
/**
 * @brief Code generator for Phasor VM
 */
class CodeGenerator
{
  public:
	/**
	 * @brief Generate bytecode from program
	 *
	 * @param program Program to generate bytecode for
	 * @param existingVars Existing variables to use
	 * @param nextVarIdx Next available variable index
	 * @param replMode REPL mode
	 * @return Bytecode Generated bytecode
	 */
	Bytecode generate(const AST::Program &program, const std::unordered_map<std::string, int> &existingVars = {},
	                  int nextVarIdx = 0, bool replMode = false);

  private:
	Bytecode bytecode;       ///< Generated bytecode
	bool     isRepl = false; ///< REPL mode
	/// @brief Functions that survive dead-code elimination (empty = DCE not yet run).
	std::unordered_set<std::string> liveFunctions;
	// Inferred types for variables (simple, flow-insensitive mapping)
	std::unordered_map<std::string, ValueType> inferredTypes;
	std::unordered_map<std::string, std::unordered_map<std::string, ValueType>> inferredFieldTypes;
	std::unordered_map<std::string, std::string> declaredTypes;

	std::string currentFunctionReturnType;
	std::vector<int> currentFunctionReturnDims;
	bool currentFunctionHasReturn = false;
	std::unordered_map<std::string, std::vector<int>> arrayDimensions;
	std::unordered_map<std::string, std::string> arrayBaseTypes;

	std::unordered_set<std::string> forwardDecls;

	// Register allocation for v2.0
	u8           nextRegister = 0; ///< Next available register
	std::vector<bool> registerInUse;    ///< Track which registers are in use

	struct ScopeFrame {
		std::vector<std::pair<int, std::string>>                    declaredIndices;
		std::unordered_map<std::string, int>                        savedBindings;
		std::unordered_map<std::string, std::optional<ValueType>>   savedInferredTypes;
		std::unordered_map<std::string, std::optional<std::string>> savedArrayBaseTypes;
		std::unordered_map<std::string, std::optional<std::vector<int>>> savedArrayDimensions;
		std::unordered_map<std::string, std::optional<std::string>> savedDeclaredTypes;
	};
	std::vector<ScopeFrame> scopeStack;

	/// @brief Allocate a new register
	u8 allocateRegister()
	{
		for (size_t i = 0; i < MAX_REGISTERS; i++)
		{
			if (i >= registerInUse.size())
			{
				registerInUse.resize(i + 1, false);
			}
			if (!registerInUse[i])
			{
				registerInUse[i] = true;
				return static_cast<u8>(i);
			}
		}
		throw std::runtime_error("Out of registers");
	}

	/// @brief Free a register
	void freeRegister(u8 reg)
	{
		if (reg < registerInUse.size())
		{
			registerInUse[reg] = false;
		}
	}

	/// @brief Reset register allocator
	void resetRegisters()
	{
		registerInUse.clear();
		nextRegister = 0;
	}

	/// @brief Check if expression is a compile-time literal
	static bool isLiteralExpression(const AST::Expression *expr, Value &outValue);

	/// @brief Simple expression type inference (conservative)
	/// @param expr expression to inspect
	/// @param known set to true when a type is known
	/// @return inferred ValueType (valid only when known == true)
	ValueType inferExpressionType(const AST::Expression *expr, bool &known);

	void generateStatement(const AST::Statement *stmt);                          ///< Generate bytecode from Statement
	void generateExpression(const AST::Expression *expr, bool resultNeeded = true); ///< Generate bytecode from Expression
	void generateVarDecl(const AST::VarDecl *varDecl);                 ///< Generate bytecode from Variable Declaration
	void generateExpressionStmt(const AST::ExpressionStmt *exprStmt);  ///< Generate bytecode from Expression Statement
	void generatePrintStmt(const AST::PrintStmt *printStmt);           ///< Generate bytecode from Print Statement
	void generateImportStmt(const AST::ImportStmt *importStmt);        ///< Generate bytecode from Import Statement
	void generateExportStmt(const AST::ExportStmt *exportStmt);        ///< Generate bytecode from Export Statement
	void generateNumberExpr(const AST::NumberExpr *numExpr);           ///< Generate bytecode from Numeral Expression
	void generateStringExpr(const AST::StringExpr *strExpr);           ///< Generate bytecode from String Expression
	void generateIdentifierExpr(const AST::IdentifierExpr *identExpr); ///< Generate bytecode from Identifier Expression
	void generateUnaryExpr(const AST::UnaryExpr *unaryExpr);           ///< Generate bytecode from Unary Expression
	void generateCallExpr(const AST::CallExpr *callExpr);              ///< Generate bytecode from Call Expression
	void generateBinaryExpr(const AST::BinaryExpr *binExpr, ValueType hint = ValueType::Null);           ///< Generate bytecode from Binary Expression
	void generateBlockStmt(const AST::BlockStmt *blockStmt);           ///< Generate bytecode from Block Statement
	void generateIfStmt(const AST::IfStmt *ifStmt);                    ///< Generate bytecode from If Statement
	void generateWhileStmt(const AST::WhileStmt *whileStmt);           ///< Generate bytecode from While Statement
	void generateForStmt(const AST::ForStmt *forStmt);                 ///< Generate bytecode from For Statement
	void generateReturnStmt(const AST::ReturnStmt *returnStmt);        ///< Generate bytecode from Return Statement
	void generateUnsafeBlockStmt(
	    const AST::UnsafeBlockStmt *unsafeStmt);                  ///< Generate bytecode from Unsafe Block Statement
	void generateFunctionDecl(const AST::FunctionDecl *funcDecl); ///< Generate bytecode from Function Declaration
	void generateBooleanExpr(const AST::BooleanExpr *boolExpr);   ///< Generate bytecode from Boolean Expression
	void generateNullExpr(const AST::NullExpr *nullExpr);         ///< Generate bytecode from Null Expression
	void generateAssignmentExpr(
	    const AST::AssignmentExpr *assignExpr); ///< Generate bytecode from Assignment Expression
	void generateStructDecl(const AST::StructDecl *decl);
	void generateStructInstanceExpr(const AST::StructInstanceExpr *expr);
	void generateFieldAccessExpr(const AST::FieldAccessExpr *expr);
	void generatePostfixExpr(const AST::PostfixExpr *expr, bool resultNeeded = true);
	void generateBreakStmt();
	void generateContinueStmt();
	void generateSwitchStmt(const AST::SwitchStmt *switchStmt);
	void generateDefaultArray(const std::vector<int> &dims, size_t dimIdx, const std::string &baseTypeName);
	void generateArrayLiteralExpr(const AST::ArrayLiteralExpr *arrayLit, bool resultNeeded);
	void generateArrayAccessExpr(const AST::ArrayAccessExpr *arrayAccess, bool resultNeeded);

	ValueType mapTypeNameToValueType(const std::string &typeName);

	// Loop context for break/continue
	std::vector<int>              loopStartStack;     // Stack of loop start positions
	std::vector<std::vector<int>> breakJumpsStack;    // Stack of break jump positions to patch
	std::vector<std::vector<int>> continueJumpsStack; // Stack of continue jump positions to patch

	int switchCounter = 0; // Monotonic counter for unique switch temp variable names
};

} // namespace Phasor