#pragma once
#include "../AST/AST.hpp"
#ifndef CMAKE_PCH
#include <Value.hpp>
#endif
#include "../ISA/ISA.hpp"
#include <phsint.hpp>
#include <map>
#include <unordered_map>
#include <string>
#include <vector>

#include <platform.h>

namespace Phasor
{
/// @brief Instruction with up to 5 operands
/// Format: instruction operand1, operand2, operand3
/// Each instruction uses only the operands it needs
struct Instruction
{
	OpCode  op;       ///< Operation code
	i32 operand1; ///< First operand
	i32 operand2; ///< Second operand
	i32 operand3; ///< Third operand

	// Default constructor
	Instruction() : op(OpCode::HALT), operand1(0), operand2(0), operand3(0)
	{
	}

	// Full constructor
	Instruction(OpCode op, i32 op1 = 0, i32 op2 = 0, i32 op3 = 0)
	    : op(op), operand1(op1), operand2(op2), operand3(op3)
	{
	}
};

/// @brief Struct metadata stored alongside bytecode (struct section)
struct StructInfo
{
    std::string              name;
    int                      firstConstIndex;
    int                      fieldCount;
    std::vector<std::string> fieldNames;
    std::vector<std::vector<int>> fieldArrayDims;
    std::vector<std::string>      fieldTypeNames;
};

/// @brief Complete bytecode structure
struct Bytecode
{
	std::vector<Instruction>             instructions;        ///< List of instructions
	std::vector<Value>                   constants;           ///< Constant pool
	std::unordered_map<std::string, int> variables;           ///< Variable name -> index mapping
	std::unordered_map<std::string, int> functionEntries;     ///< Function name -> instruction index mapping
	std::unordered_map<std::string, int> functionParamCounts; ///< Function name -> parameter count
	std::unordered_map<std::string, std::vector<std::string>> functionParamTypeNames; ///< Function name -> parameter type names
	std::unordered_map<std::string, std::vector<std::vector<int>>> functionParamArrayDims;
	std::unordered_map<std::string, std::string> functionReturnTypeNames; ///< Function name -> return type name
	int                                  nextVarIndex = 0;    ///< Next available variable index

	// Struct section (planned usage by future struct codegen)
	std::vector<StructInfo>              structs;       ///< List of struct descriptors
	std::unordered_map<std::string, int> structEntries; ///< Struct name -> index in structs

	/// @brief Add a constant to the pool and return its index
	int addConstant(const Value &value)
	{
		constants.push_back(value);
		return static_cast<int>(constants.size()) - 1;
	}

	/// @brief Add a string constant with deduplication
	int addStringConstant(const std::string &s)
	{
		auto it = stringConstantCache.find(s);
		if (it != stringConstantCache.end())
		{
			return it->second;
		}
		int idx = addConstant(Value(s));
		stringConstantCache[s] = idx;
		return idx;
	}

	std::unordered_map<std::string, int> stringConstantCache; ///< Dedup cache for string constants

	/// @brief Get or create a variable index
	int getOrCreateVar(const std::string &name)
	{
		auto it = variables.find(name);
		if (it != variables.end())
		{
			return it->second;
		}
		int index = nextVarIndex++;
		variables[name] = index;
		return index;
	}

	/// @brief Emit an instruction with operands
	void emit(OpCode op, i32 op1 = 0, i32 op2 = 0, i32 op3 = 0)
	{
		instructions.emplace_back(op, op1, op2, op3);
	}
};

/**
 * @brief Code generator for Phasor VM
 */
class CodeGenerator
{
  public:
	/**
	 * @brief Generate bytecode from program
	 *
	 * @param program Program to generate bytecode for
	 * @param existingVars Existing variables to use
	 * @param nextVarIdx Next available variable index
	 * @param replMode REPL mode
	 * @return Bytecode Generated bytecode
	 */
	Bytecode generate(const AST::Program &program, const std::unordered_map<std::string, int> &existingVars = {},
	                  int nextVarIdx = 0, bool replMode = false);

  private:
	Bytecode bytecode;       ///< Generated bytecode
	bool     isRepl = false; ///< REPL mode
	// Inferred types for variables (simple, flow-insensitive mapping)
	std::unordered_map<std::string, ValueType> inferredTypes;
	std::string currentFunctionReturnType;
	std::unordered_map<std::string, std::vector<int>> arrayDimensions;

	// Register allocation for v2.0
	u8           nextRegister = 0; ///< Next available register
	std::vector<bool> registerInUse;    ///< Track which registers are in use

	/// @brief Allocate a new register
	u8 allocateRegister()
	{
		for (size_t i = 0; i < MAX_REGISTERS; i++)
		{
			if (i >= registerInUse.size())
			{
				registerInUse.resize(i + 1, false);
			}
			if (!registerInUse[i])
			{
				registerInUse[i] = true;
				return static_cast<u8>(i);
			}
		}
		throw std::runtime_error("Out of registers");
	}

	/// @brief Free a register
	void freeRegister(u8 reg)
	{
		if (reg < registerInUse.size())
		{
			registerInUse[reg] = false;
		}
	}

	/// @brief Reset register allocator
	void resetRegisters()
	{
		registerInUse.clear();
		nextRegister = 0;
	}

	/// @brief Check if expression is a compile-time literal
	static bool isLiteralExpression(const AST::Expression *expr, Value &outValue);

	/// @brief Simple expression type inference (conservative)
	/// @param expr expression to inspect
	/// @param known set to true when a type is known
	/// @return inferred ValueType (valid only when known == true)
	ValueType inferExpressionType(const AST::Expression *expr, bool &known);

	void generateStatement(const AST::Statement *stmt);                          ///< Generate bytecode from Statement
	void generateExpression(const AST::Expression *expr, bool resultNeeded = true); ///< Generate bytecode from Expression
	void generateVarDecl(const AST::VarDecl *varDecl);                 ///< Generate bytecode from Variable Declaration
	void generateExpressionStmt(const AST::ExpressionStmt *exprStmt);  ///< Generate bytecode from Expression Statement
	void generatePrintStmt(const AST::PrintStmt *printStmt);           ///< Generate bytecode from Print Statement
	void generateImportStmt(const AST::ImportStmt *importStmt);        ///< Generate bytecode from Import Statement
	void generateExportStmt(const AST::ExportStmt *exportStmt);        ///< Generate bytecode from Export Statement
	void generateNumberExpr(const AST::NumberExpr *numExpr);           ///< Generate bytecode from Numeral Expression
	void generateStringExpr(const AST::StringExpr *strExpr);           ///< Generate bytecode from String Expression
	void generateIdentifierExpr(const AST::IdentifierExpr *identExpr); ///< Generate bytecode from Identifier Expression
	void generateUnaryExpr(const AST::UnaryExpr *unaryExpr);           ///< Generate bytecode from Unary Expression
	void generateCallExpr(const AST::CallExpr *callExpr);              ///< Generate bytecode from Call Expression
	void generateBinaryExpr(const AST::BinaryExpr *binExpr);           ///< Generate bytecode from Binary Expression
	void generateBlockStmt(const AST::BlockStmt *blockStmt);           ///< Generate bytecode from Block Statement
	void generateIfStmt(const AST::IfStmt *ifStmt);                    ///< Generate bytecode from If Statement
	void generateWhileStmt(const AST::WhileStmt *whileStmt);           ///< Generate bytecode from While Statement
	void generateForStmt(const AST::ForStmt *forStmt);                 ///< Generate bytecode from For Statement
	void generateReturnStmt(const AST::ReturnStmt *returnStmt);        ///< Generate bytecode from Return Statement
	void generateUnsafeBlockStmt(
	    const AST::UnsafeBlockStmt *unsafeStmt);                  ///< Generate bytecode from Unsafe Block Statement
	void generateFunctionDecl(const AST::FunctionDecl *funcDecl); ///< Generate bytecode from Function Declaration
	void generateBooleanExpr(const AST::BooleanExpr *boolExpr);   ///< Generate bytecode from Boolean Expression
	void generateNullExpr(const AST::NullExpr *nullExpr);         ///< Generate bytecode from Null Expression
	void generateAssignmentExpr(
	    const AST::AssignmentExpr *assignExpr); ///< Generate bytecode from Assignment Expression
	void generateStructDecl(const AST::StructDecl *decl);
	void generateStructInstanceExpr(const AST::StructInstanceExpr *expr);
	void generateFieldAccessExpr(const AST::FieldAccessExpr *expr);
	void generatePostfixExpr(const AST::PostfixExpr *expr, bool resultNeeded = true);
	void generateBreakStmt();
	void generateContinueStmt();
	void generateSwitchStmt(const AST::SwitchStmt *switchStmt);
	void generateArrayLiteralExpr(const AST::ArrayLiteralExpr *arrayLit, bool resultNeeded);
	void generateArrayAccessExpr(const AST::ArrayAccessExpr *arrayAccess, bool resultNeeded);

	ValueType mapTypeNameToValueType(const std::string &typeName);

	// Loop context for break/continue
	std::vector<int>              loopStartStack;     // Stack of loop start positions
	std::vector<std::vector<int>> breakJumpsStack;    // Stack of break jump positions to patch
	std::vector<std::vector<int>> continueJumpsStack; // Stack of continue jump positions to patch

	std::unordered_map<std::string, std::string> arrayBaseTypes;

	int switchCounter = 0; // Monotonic counter for unique switch temp variable names
};

} // namespace Phasor