<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Phasor</string>
        <key>scopeName</key>
        <string>source.phasor</string>
        <key>fileTypes</key>
        <array>
            <string>phs</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#keywords</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#strings</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#numbers</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#operators</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#functions</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#types</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.line.double-slash.phasor</string>
                        <key>match</key>
                        <string>//.*$</string>
                    </dict>
                </array>
            </dict>
            <key>keywords</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.phasor</string>
                        <key>match</key>
                        <string>\b(if|else|while|for|switch|case|default|break|continue|return)\b</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>keyword.declaration.phasor</string>
                        <key>match</key>
                        <string>\b(var|const|fn|struct|import|export|unsafe)\b</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.phasor</string>
                        <key>match</key>
                        <string>\b(true|false|null)\b</string>
                    </dict>
                </array>
            </dict>
            <key>strings</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.double.phasor</string>
                        <key>begin</key>
                        <string>"</string>
                        <key>end</key>
                        <string>"</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>name</key>
                                <string>constant.character.escape.phasor</string>
                                <key>match</key>
                                <string>\\.</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>numbers</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>constant.numeric.phasor</string>
                        <key>match</key>
                        <string>\b\d+(\.\d+)?\b</string>
                    </dict>
                </array>
            </dict>
            <key>operators</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.phasor</string>
                        <key>match</key>
                        <string>(\+\+|--|==|!=|&lt;=|&gt;=|&amp;&amp;|\|\||-&gt;|[+\-*/%&lt;&gt;=!&amp;|.])</string>
                    </dict>
                </array>
            </dict>
            <key>functions</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>entity.name.function.phasor</string>
                        <key>match</key>
                        <string>\b([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>support.function.phasor</string>
                        <key>match</key>
                        <string>\b(include_stdio|include_stdmath|include_stdstr|include_stdfile|include_stdsys|include_stdtype|include_stdregex|puts|printf|gets|putf|msgbox|math_sqrt|math_pow|math_sin|math_cos|len|substr|concat|to_upper|to_lower|fread|fwrite|fexists|fcopy|fmove|time|sleep|sys_os|sys_exec|clear|to_int|to_float|to_string|to_bool|regex_match|regex_search|regex_replace)\b</string>
                    </dict>
                </array>
            </dict>
            <key>types</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>storage.type.phasor</string>
                        <key>match</key>
                        <string>\b(int|float|string|bool)\b</string>
                    </dict>
                </array>
            </dict>
        </dict>
    </dict>
</plist>