<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Phasor IR</string>
	<key>scopeName</key>
	<string>source.phasor-ir</string>
	<key>fileTypes</key>
	<array>
		<string>phir</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#opcodes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#registers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.semicolon.phasor-ir</string>
					<key>match</key>
					<string>;.*$</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.section.phasor-ir</string>
					<key>match</key>
					<string>^\.(PHIR|CONSTANTS|VARIABLES|FUNCTIONS|FUNCTYPES|STRUCTS|INSTRUCTIONS)\b</string>
				</dict>
			</array>
		</dict>
		<key>opcodes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.opcode.phasor-ir</string>
					<key>match</key>
					<string>\b(PUSH_CONST|POP|IADD|ISUBTRACT|IMULTIPLY|IDIVIDE|IMODULO|FLADD|FLSUBTRACT|FLMULTIPLY|FLDIVIDE|FLMODULO|SQRT|POW|LOG|EXP|SIN|COS|TAN|NEGATE|NOT|IAND|IOR|IEQUAL|INOT_EQUAL|ILESS_THAN|IGREATER_THAN|ILESS_EQUAL|IGREATER_EQUAL|FLAND|FLOR|FLEQUAL|FLNOT_EQUAL|FLLESS_THAN|FLGREATER_THAN|FLLESS_EQUAL|FLGREATER_EQUAL|JUMP|JUMP_IF_FALSE|JUMP_IF_TRUE|JUMP_BACK|STORE_VAR|LOAD_VAR|PRINT|PRINTERROR|READLINE|IMPORT|HALT|CALL_NATIVE|CALL|SYSTEM|SYSTEM_OUT|SYSTEM_ERR|RETURN|TRUE|FALSE|NULL_VAL|LEN|CHAR_AT|SUBSTR|MOV|LOAD_CONST_R|LOAD_VAR_R|STORE_VAR_R|IADD_R|ISUB_R|IMUL_R|IDIV_R|IMOD_R|FLADD_R|FLSUB_R|FLMUL_R|FLDIV_R|FLMOD_R|SQRT_R|POW_R|LOG_R|EXP_R|SIN_R|COS_R|TAN_R|IAND_R|IOR_R|IEQ_R|INE_R|ILT_R|IGT_R|ILE_R|IGE_R|FLAND_R|FLOR_R|FLEQ_R|FLNE_R|FLLT_R|FLGT_R|FLLE_R|FLGE_R|PUSH_R|PUSH2_R|POP_R|POP2_R|NEG_R|NOT_R|PRINT_R|PRINTERROR_R|READLINE_R|SYSTEM_R|SYSTEM_OUT_R|SYSTEM_ERR_R)\b</string>
				</dict>
			</array>
		</dict>
		<key>registers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.register.phasor-ir</string>
					<key>match</key>
					<string>\br\d+\b</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.constant.phasor-ir</string>
					<key>match</key>
					<string>\b(NULL|BOOL|INT|FLOAT|STRING)\b</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.phasor-ir</string>
					<key>match</key>
					<string>\b\d+(\.\d+)?\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.phasor-ir</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.phasor-ir</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
