<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Phasor IR</string>
	<key>scopeName</key>
	<string>source.phasor-ir</string>
	<key>fileTypes</key>
	<array>
		<string>phir</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#sections</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#opcodes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#registers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line.semicolon.phasor-ir</string>
					<key>match</key>
					<string>;.*$</string>
				</dict>
			</array>
		</dict>
		<key>sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.control.section.phasor-ir</string>
					<key>match</key>
					<string>^\.(PHIR|CONSTANTS|VARIABLES|FUNCTIONS|STRUCTS|INSTRUCTIONS)\b</string>
				</dict>
			</array>
		</dict>
		<key>opcodes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator.opcode.phasor-ir</string>
					<key>match</key>
					<string>\b(PUSH_CONST|POP|ADD|SUBTRACT|MULTIPLY|DIVIDE|MODULO|SQRT|POW|LOG|EXP|SIN|COS|TAN|NEGATE|NOT|AND|OR|EQUAL|NOT_EQUAL|LESS_THAN|GREATER_THAN|LESS_EQUAL|GREATER_EQUAL|JUMP|JUMP_IF_FALSE|JUMP_IF_TRUE|JUMP_BACK|STORE_VAR|LOAD_VAR|PRINT|PRINTERROR|READLINE|IMPORT|HALT|CALL_NATIVE|CALL|SYSTEM|RETURN|TRUE|FALSE|NULL_VAL|LEN|CHAR_AT|SUBSTR|MOV|LOAD_CONST_R|LOAD_VAR_R|STORE_VAR_R|ADD_R|SUB_R|MUL_R|DIV_R|MOD_R|SQRT_R|POW_R|LOG_R|EXP_R|SIN_R|COS_R|TAN_R|AND_R|OR_R|EQ_R|NE_R|LT_R|GT_R|LE_R|GE_R|PUSH_R|PUSH2_R|POP_R|POP2_R|NEG_R|NOT_R|PRINT_R|PRINTERROR_R|READLINE_R|SYSTEM_R)\b</string>
				</dict>
			</array>
		</dict>
		<key>registers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>variable.parameter.register.phasor-ir</string>
					<key>match</key>
					<string>\br\d+\b</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>storage.type.constant.phasor-ir</string>
					<key>match</key>
					<string>\b(NULL|BOOL|INT|FLOAT|STRING)\b</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric.phasor-ir</string>
					<key>match</key>
					<string>\b\d+(\.\d+)?\b</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>string.quoted.double.phasor-ir</string>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>constant.character.escape.phasor-ir</string>
							<key>match</key>
							<string>\\.</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
