DWORD GetTickCount(void);
DWORD GetTickCount64(void);
DWORD GetCurrentProcessId(void);
DWORD GetCurrentThreadId(void);
DWORD GetLastError(void);
DWORD GetVersion(void);
BOOL  Beep(DWORD dwFreq, DWORD dwDuration);
DWORD GetEnvironmentVariableA(LPCSTR lpName, LPSTR lpBuffer, DWORD nSize);
DWORD GetEnvironmentVariableW(LPCWSTR lpName, LPWSTR lpBuffer, DWORD nSize);
BOOL  SetEnvironmentVariableA(LPCSTR lpName, LPCSTR lpValue);
BOOL  SetEnvironmentVariableW(LPCWSTR lpName, LPCWSTR lpValue);
UINT  GetACP(void);
UINT  GetOEMCP(void);
UINT  GetConsoleCP(void);
UINT  GetConsoleOutputCP(void);
ULONG MulDiv(ULONG nNumber, ULONG nNumerator, ULONG nDenominator);
int   MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
int   MessageBoxW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType);
int  MessageBoxTimeoutA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType, WORD wLanguageId, DWORD dwMilliseconds);
int  MessageBoxTimeoutW(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType, WORD wLanguageId,
                        DWORD dwMilliseconds);
BOOL SetCursorPos(int X, int Y);
BOOL GetCursorPos(LPPOINT lpPoint);
int  GetSystemMetrics(int nIndex);
BOOL ShowWindow(HWND hWnd, int nCmdShow);
BOOL EnableWindow(HWND hWnd, BOOL bEnable);
HWND GetForegroundWindow();
HWND GetDesktopWindow();
HANDLE    GetStdHandle(DWORD nStdHandle);
HMODULE   GetModuleHandleA(LPCSTR lpModuleName);
HMODULE   GetModuleHandleW(LPCWSTR lpModuleName);
HINSTANCE LoadLibraryA(LPCSTR lpLibFileName);
HINSTANCE LoadLibraryW(LPCWSTR lpLibFileName);
BOOL      CloseHandle(HANDLE hObject);
BOOL      IsWindow(HWND hWnd);
BOOL      SetWindowTextA(HWND hWnd, LPCSTR lpString);
BOOL      SetWindowTextW(HWND hWnd, LPCWSTR lpString);
BOOL      GetWindowTextA(HWND hWnd, LPSTR lpString, int nMaxCount);
BOOL      GetWindowTextW(HWND hWnd, LPWSTR lpString, int nMaxCount);
BOOL      ShowCursor(BOOL bShow);
UINT      GetWindowsDirectoryA(LPSTR lpBuffer, UINT uSize);
UINT      GetWindowsDirectoryW(LPWSTR lpBuffer, UINT uSize);
