if(WIN32)
    if(ASSEMBLY)
        enable_language(ASM_MASM)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/crt/arithmetic.c)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/crt/logical.c)
    else()
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/x86_64/arithmetic_windows.asm)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/x86_64/logical_windows.asm)
    endif()
elseif(APPLE)
    if(ASSEMBLY)
        enable_language(ASM)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/crt/arithmetic.c)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/crt/logical.c)
    else()
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/x86_64/arithmetic_osx.s)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/x86_64/logical_osx.s)
    endif()
elseif(UNIX OR CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
    if(ASSEMBLY)
        enable_language(ASM)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/crt/arithmetic.c)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/crt/logical.c)
    else()
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/x86_64/arithmetic_systemv.s)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/native/x86_64/logical_systemv.s)
    endif()
endif()