if(WIN32)
    if(ASSEMBLY)
        enable_language(ASM_MASM)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/arithmetic/crt.c)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/logical/crt.c)
    else()
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/arithmetic/windows_x86_64.asm)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/logical/windows_x86_64.asm)
    endif()
elseif(APPLE OR CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
    if(ASSEMBLY)
        enable_language(ASM)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/arithmetic/crt.c)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/logical/crt.c)
    else()
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/arithmetic/bsd_x86_64.s)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/logical/bsd_x86_64.s)
    endif()
elseif(UNIX)
    if(ASSEMBLY)
        enable_language(ASM)
    endif()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/arithmetic/crt.c)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/logical/crt.c)
    else()
        set(ARITHMETIC_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/arithmetic/linux_x86_64.s)
        set(LOGICAL_ASM ${CMAKE_SOURCE_DIR}/src/Runtime/VM/core/logical/linux_x86_64.s)
    endif()
endif()