name: CMake Multi-Platform Build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc-14
            cpp_compiler: g++-14
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up MSVC
      if: matrix.os == 'windows-2025-vs2026'
      uses: egor-tensin/vs-shell@v2
      with:
        arch: x64

    - name: Install GCC 14 (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y g++-14
    
    - name: Configure (macOS)
      if: matrix.os == 'macos-latest'
      shell: bash
      run: cmake -S . -G Ninja -B build -DASSEMBLY=OFF -DIS_TRACING=ON -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=RelWithDebInfo

    - name: Configure 
      if: matrix.os != 'macos-latest'
      shell: bash
      run: cmake -S . -G Ninja -B build -DIS_TRACING=ON -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=RelWithDebInfo
    
    - name: Build
      shell: bash
      run: cmake --build build --config Release

    - name: Test 
      shell: bash
      run: ./build/src/Executable/phasor ./scripts/unittest.phs
