name: CMake Multi-Platform Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2025-vs2026
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc-16
            cpp_compiler: g++-16
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      with:
        persist-credentials: false

    - name: Set up MSVC (Windows)
      if: matrix.os == 'windows-2025-vs2026'
      uses: egor-tensin/vs-shell@54e4148eac794e4580591c2e0b7750f14b7891fc # v2
      with:
        arch: x64

    - name: Install GCC 16 (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get install -y gcc-16 g++-16
    
    - name: Configure (macOS)
      if: matrix.os == 'macos-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: cmake -S . -G Ninja -B build -DASSEMBLY=OFF -DIS_TRACING=ON -DNATIVE=ON -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=Release

    - name: Configure (Windows/Linux)
      if: matrix.os != 'macos-latest'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash
      run: cmake -S . -G Ninja -B build -DNATIVE=ON -DIS_TRACING=ON -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      shell: bash
      run: cmake --build build --config Release

    - name: Test 
      shell: bash
      env:
        PHASOR_INCLUDE_PATH: ${{ github.workspace }}/src/Runtime/Stdlib/phasor
      run: ./build/src/Executable/phasor ./scripts/unittest.phs
